### ISSUE TITLE
0.13 - 0.14 upgrade breaks when calling memoized_methods from a child class

### ISSUE THREAD

**Issue by januszm** [matthewrudy/memoist#51]
After upgrading from 0.13 to 0.14 on Rails 4.2.7.1 app I get those errors from a child class of:

``` ruby
class AbstractService
  extend Memoist
```

 module:

`undefined method 'memoized_methods' for AbstractService:Class`

adding `require 'memoist'` at the top of the file does **not** resolve the issue.

**Comment by matthewrudy** [comment]
@januszm can you explain what happens?

The basics definitely work for me.

**Comment by januszm** [comment]
Funny, on Rails 5.0.0.1 it doesn't even know the Memois module and I can't use ```require 'memoist'``` because it says no such file.

Anyway, on Rails 4.2.7.1 I get this in a call to ```flush_cache``` method.

```ruby
class AbstractService
  extend Memoist

  def run
    flush_cache if respond_to?(:flush_cache)
```

**Comment by matthewrudy** [comment]
I think something else must be at play.

Can you try turning off backtrace silencers

```
# /config/initializers/backtrace_silencers.rb
Rails.backtrace_cleaner.remove_silencers!
```

And see where the actual error comes from

**Comment by januszm** [comment]
Now it shows line 102 in ```lib/memoist.rb```

```ruby
# an ancestor method.
ancestors.grep(Memoist).each do |ancestor|
  ancestor.memoized_methods.each do |m|
    structs << m unless structs.any? {|am| am.memoized_method == m.memoized_method }
  end
end
```

**Comment by januszm** [comment]
hmm, yeah this piece of code was added between v0.13.0 and v0.14.0, how about this dirty quick fix?

```ruby
ancestor.memoized_methods.each do |m|
  structs << m unless structs.any? {|am| am.memoized_method == m.memoized_method }
end if ancestor.respond_to?(:memoized_methods)

**Comment by januszm** [comment]
@matthewrudy just to be clear, I ommitted this before. I get this error from a child class that inherits from the AbstractService. Maybe this is happening:

1. Parent class extends Memoist module but doesn't make a call to ```memoize```
2. Child class calls ```memoize_methods``` on its ```ancestor``` (which is Parent class)

And here we get the undefined method error because this portion of code wasn't executed:

```ruby
def memoize(*method_names)
  ...
  Memoist.memoist_eval(self) do
    def self.memoized_methods
```

because there's no call to #memoize in the Parent, AbstractService class in my case.

Anyway, the current implementation makes using inheritance harder.

**Comment by matthewrudy** [comment]
@januszm that makes sense.

So I guess we can reproduce with a test.

**Comment by matthewrudy** [comment]
I tried adding this test
and its passes

``` ruby
def test_memoization_where_superclass_doesnt_call_memoize
    a = Class.new
    a.extend Memoist
    b = Class.new(a) do
      def foo
        @foo_count ||= 0
        @foo_count += 1
        "foo #{@foo_count}"
      end
      memoize :foo
    end

    obj = b.new
    2.times do
      assert_equal "foo 1", obj.foo
    end
  end
```

**Comment by januszm** [comment]
Here's my example that fails:

```ruby
class Abb
  extend Memoist
  
  def run(*args)
    flush_cache if respond_to?(:flush_cache)
    execute
  end


  protected

  def execute
    # Override this
  end
end  

class Bbb < Abb
  protected

  def execute
    some_method
  end

  def some_method
    'FooBar'
  end
  memoize :some_method
end

x = Bbb.new
x.run

NoMethodError: undefined method `memoized_methods' for Abb:Class
```

**Comment by januszm** [comment]
It works if I remove the call to ```flush_cache``` so this is the place where problems arise

**Comment by matthewrudy** [comment]
@januszm I get it.

Actually I guess it's enough to say

``` ruby
class Foo
  extend Memoist
end

Foo.new.flush_cache
```

Let me work out why we don't define `memoized_methods` when we extend

**Comment by ccmcbeck** [comment]
@matthewrudy - any progress?  I have several class methods on a Device model that I `memoize` then use `Device.flush_cache` in an RSpec `config.before` block.  Not why we do that -- it's legacy code.

**Comment by PikachuEXE** [comment]
I got the same issue too

**Comment by PikachuEXE** [comment]
Submitted a fix in #68
